### PR TITLE
Large migration to updated dependencies

### PR DESCRIPTION
**Pull request by Lucretiel**
A lot of stuff was either throwing security warnings or just not working as expected, so I've done a massive refactor of the dependencies and rewritten stuff where necessary. Build + Run is succeeding with these changes.

### CODE REVIEW

**Comment by diminishedprime** [comment]
Can I wait to review this till you get in the eslint one? I figure that'll get rid of a lot of the diff on this one.

**Comment by Lucretiel** [comment]
Yes, by all means. I was hoping github was smart enough to detect dependent PRs but I guess not.

**Comment by Lucretiel** [comment]
Done

**Comment by Lucretiel** [comment]
Same thing; I'm planning to resolve all outstanding merge & test failures in https://github.com/Lucretiel/ga-dev-tools/tree/dimensions-metrics-explorer; it's too hard to prevent merge conflicts when the work is done in separate branches.

**Pull request merged**
