### PR TITLE
Add firstDayOfMonth to data-range-selector

### PR DESCRIPTION
**Pull request by sh0hei**

### CODE REVIEW

**Comment by Lucretiel** [comment]
Added some simplifications; let me know what you think and I'll merge.

This seems good, but does it actually appear on any of the pages anywhere? I looked through everything at https://ga-dev-tools.appspot.com/embed-api/ and couldn't find a place where that selector is actually used. If you just like it as a feature in the component, that's fine too.

**Comment by sh0hei** [comment]
I fixed it a bit for get current month.
selector is used in https://ga-dev-tools.appspot.com/query-explorer/ `start-date` `end-date`

**Comment by Lucretiel** [comment]
Ah, good catch! That looks good, ty for the branch

**Comment by Lucretiel** [comment]
Quick note: while the change is fine, I don't think that it affects that query explorer component. The code you edited is part of the embed API pages. The query explorer has a separate, server-side mechanism for interpreting the special date strings.

Were you able to run a local version of this code for testing? Feel free to set it up and reach out to me with any questions or issues.

**Pull request merged**
